### ISSUE TITLE
Not abug but a livesign that the work is in progrss

### ISSUE THREAD

**Issue by jakespeed1311** [khoih-prog/AsyncFSWebServer_Teensy41#2]
HI,
Sorry if this is not the right place, but i want that you know that i have started. I am not familiar with git operations, at this moment.

i have some troube to bring files t the Teensy , now i have add the Teensy MTP to the Sourcecode. To be able to copy teh files to to LittleFS.
From the PC and form Teensy Programm i can see that now. Hurray.

Next step is to check out why on my tests the website was not found from Async SerfeStatic on the FS.

greedings
Jake

**Comment by khoih-prog** [comment]
I'm glad that you've started testing and moving ahead.

You can forked this library and update / modify your local copy to test. Then when it's better, make a PR to merge from time to time, so that other people can use that new enhancement.

You can also post code, examples here

**Comment by strud** [comment]
@jakespeed1311  Iam very interested in this as well, however my experience in this are is limited. I will help where I can and as a minimum can assist with testing.

**Comment by khoih-prog** [comment]
@jakespeed1311 

Any progress on your side? I guess many more people are interested in what you're doing and achieving.

Give us some update, or update your GitHub copy with some notes.

Thanks,

**Comment by jakespeed1311** [comment]
@khoih-prog  Quick answer unfortunately no. 
Unfortunately I don't have time to program at the moment.
I myself burn for it but there are currently more important private tasks that need my time and energy.
I don't have an outlook when I can continue working.

I but the FTP Teensy server seen, very cool!
My biggest problem is still to get the files without much effort on the Littlefs.
Currently SD copy on Littlefs.... well
But to access via the Async then I did not succeed so far.

Thanks that you started this AsyncFS!



Translated with www.DeepL.com/Translator (free version)

**Comment by jakespeed1311** [comment]
Hello,
now i am stuck, i found that the file was not sended, because at the end of the responce, there is only a request->send(response);)
But i feel that here schould be an send(file content.. or send( FS*

Line 283 in AsyncFSWebHandlers_Teensy41.cpp.

I can't see wehre in function Send() will be a part that send the file body itself. Maybe i am wrong.
All my files are in root of the littlef, also the index.htm what i tryed to browse.
And allway i get an Internal Server Error 500.
Sorry now iam helples.

greedings 
Jake
